package com.funkyotc.puzzleverse.generators.woodnuts

import java.io.File
import kotlin.random.Random

/**
 * Standalone Kotlin runner for generating Wood Nuts plank hole patterns into WoodNutsPregenerated.kt.
 */
fun main(args: Array<String>) {
    val targetFile = File("app/src/main/java/com/funkyotc/puzzleverse/woodnuts/data/WoodNutsPregenerated.kt")
    println("Generating Wood Nuts levels into ${targetFile.absolutePath}...")

    val sb = StringBuilder()

    sb.appendLine("package com.funkyotc.puzzleverse.woodnuts.data")
    sb.appendLine()
    sb.appendLine("import com.funkyotc.puzzleverse.core.data.BrowseablePuzzle")
    sb.appendLine()
    sb.appendLine("data class PregeneratedWoodNutsLevel(")
    sb.appendLine("    override val id: String,")
    sb.appendLine("    override val difficulty: String,")
    sb.appendLine("    val rows: Int,")
    sb.appendLine("    val cols: Int,")
    sb.appendLine("    val bolts: List<Bolt>,")
    sb.appendLine("    val planks: List<Plank>,")
    sb.appendLine("    val boardQueue: List<ScrewColor> = emptyList()")
    sb.appendLine(") : BrowseablePuzzle {")
    sb.appendLine("    override val label: String get() = id.substringAfterLast('_')")
    sb.appendLine("    override val subtitle: String get() = \"\${rows}x\${cols}\"")
    sb.appendLine("}")
    sb.appendLine()
    sb.appendLine("object WoodNutsPregenerated {")
    sb.appendLine()
    sb.appendLine("    val ALL_LEVELS: List<PregeneratedWoodNutsLevel> by lazy { generateAllLevels() }")
    sb.appendLine()
    sb.appendLine("    val PUZZLES_BY_DIFFICULTY: Map<String, List<PregeneratedWoodNutsLevel>> by lazy {")
    sb.appendLine("        ALL_LEVELS.groupBy { it.difficulty }")
    sb.appendLine("    }")
    sb.appendLine()
    sb.appendLine("    fun getPuzzleById(id: String): PregeneratedWoodNutsLevel? = ALL_LEVELS.find { it.id == id }")
    sb.appendLine()
    sb.appendLine("    private fun generateAllLevels(): List<PregeneratedWoodNutsLevel> {")
    sb.appendLine("        val list = mutableListOf<PregeneratedWoodNutsLevel>()")
    sb.appendLine("        ")
    sb.appendLine("        // 10 Easy levels (3x3 - 4x4)")
    sb.appendLine("        for (i in 1..10) {")
    sb.appendLine("            list.add(createLevel(\"woodnuts_easy_\${i.toString().padStart(3, '0')}\", \"Easy\", 3 + (i % 2), i))")
    sb.appendLine("        }")
    sb.appendLine("        ")
    sb.appendLine("        // 10 Medium levels (4x4 - 5x5)")
    sb.appendLine("        for (i in 1..10) {")
    sb.appendLine("            list.add(createLevel(\"woodnuts_medium_\${i.toString().padStart(3, '0')}\", \"Medium\", 4 + (i % 2), 10 + i))")
    sb.appendLine("        }")
    sb.appendLine("        ")
    sb.appendLine("        // 10 Hard levels (5x5)")
    sb.appendLine("        for (i in 1..10) {")
    sb.appendLine("            list.add(createLevel(\"woodnuts_hard_\${i.toString().padStart(3, '0')}\", \"Hard\", 5, 20 + i))")
    sb.appendLine("        }")
    sb.appendLine("        ")
    sb.appendLine("        // 10 Expert levels (5x5 - 6x6)")
    sb.appendLine("        for (i in 1..10) {")
    sb.appendLine("            list.add(createLevel(\"woodnuts_expert_\${i.toString().padStart(3, '0')}\", \"Expert\", 5 + (i % 2), 30 + i))")
    sb.appendLine("        }")
    sb.appendLine("        ")
    sb.appendLine("        // 10 Master levels (6x6)")
    sb.appendLine("        for (i in 1..10) {")
    sb.appendLine("            list.add(createLevel(\"woodnuts_master_\${i.toString().padStart(3, '0')}\", \"Master\", 6, 40 + i))")
    sb.appendLine("        }")
    sb.appendLine("        ")
    sb.appendLine("        return list")
    sb.appendLine("    }")
    sb.appendLine()
    sb.appendLine("    private fun createLevel(id: String, difficulty: String, size: Int, seedIndex: Int): PregeneratedWoodNutsLevel {")
    sb.appendLine("        val random = kotlin.random.Random(seedIndex.toLong() * 1000L + 42L)")
    sb.appendLine("        val bolts = mutableListOf<Bolt>()")
    sb.appendLine("        val planks = mutableListOf<Plank>()")
    sb.appendLine("        ")
    sb.appendLine("        val plankCount = when (difficulty) {")
    sb.appendLine("            \"Easy\" -> 3 + (seedIndex % 2)")
    sb.appendLine("            \"Medium\" -> 5 + (seedIndex % 2)")
    sb.appendLine("            \"Hard\" -> 7 + (seedIndex % 2)")
    sb.appendLine("            \"Expert\" -> 8 + (seedIndex % 3)")
    sb.appendLine("            else -> 10 + (seedIndex % 3)")
    sb.appendLine("        }")
    sb.appendLine("        ")
    sb.appendLine("        val allCoords = mutableListOf<Pair<Int, Int>>()")
    sb.appendLine("        for (r in 0 until size) {")
    sb.appendLine("            for (c in 0 until size) {")
    sb.appendLine("                allCoords.add(Pair(r, c))")
    sb.appendLine("            }")
    sb.appendLine("        }")
    sb.appendLine("        allCoords.shuffle(random)")
    sb.appendLine("        ")
    sb.appendLine("        val rawTotal = (plankCount * 1.8f).toInt().coerceAtMost(size * size - 2)")
    sb.appendLine("        val boardCount = (rawTotal / 3).coerceAtLeast(1)")
    sb.appendLine("        val totalBolts = boardCount * 3")
    sb.appendLine("        val boltCoords = allCoords.take(totalBolts)")
    sb.appendLine("        ")
    sb.appendLine("        val availableColors = ScrewColor.entries.shuffled(random)")
    sb.appendLine("        val boardQueue = mutableListOf<ScrewColor>()")
    sb.appendLine("        val boltColors = mutableListOf<ScrewColor>()")
    sb.appendLine("        ")
    sb.appendLine("        for (b in 0 until boardCount) {")
    sb.appendLine("            val color = availableColors[b % availableColors.size]")
    sb.appendLine("            boardQueue.add(color)")
    sb.appendLine("            repeat(3) {")
    sb.appendLine("                boltColors.add(color)")
    sb.appendLine("            }")
    sb.appendLine("        }")
    sb.appendLine("        boltColors.shuffle(random)")
    sb.appendLine()
    sb.appendLine("        for ((idx, coord) in boltCoords.withIndex()) {")
    sb.appendLine("            bolts.add(Bolt(\"b\${idx + 1}\", coord.first, coord.second, color = boltColors[idx]))")
    sb.appendLine("        }")
    sb.appendLine("        ")
    sb.appendLine("        var plankId = 1")
    sb.appendLine("        for (p in 0 until plankCount) {")
    sb.appendLine("            if (bolts.size < 2) break")
    sb.appendLine("            val b1 = bolts[random.nextInt(bolts.size)]")
    sb.appendLine("            var b2 = bolts[random.nextInt(bolts.size)]")
    sb.appendLine("            while (b2.id == b1.id) {")
    sb.appendLine("                b2 = bolts[random.nextInt(bolts.size)]")
    sb.appendLine("            }")
    sb.appendLine("            ")
    sb.appendLine("            val r1 = minOf(b1.row, b2.row)")
    sb.appendLine("            val c1 = minOf(b1.col, b2.col)")
    sb.appendLine("            val r2 = maxOf(b1.row, b2.row)")
    sb.appendLine("            val c2 = maxOf(b1.col, b2.col)")
    sb.appendLine("            ")
    sb.appendLine("            val extraBolts = bolts.filter { b ->")
    sb.appendLine("                b.id != b1.id && b.id != b2.id &&")
    sb.appendLine("                b.row in r1..r2 && b.col in c1..c2 &&")
    sb.appendLine("                (random.nextFloat() < 0.4f)")
    sb.appendLine("            }.map { it.id }")
    sb.appendLine("            ")
    sb.appendLine("            val attachedBolts = (listOf(b1.id, b2.id) + extraBolts).distinct()")
    sb.appendLine("            ")
    sb.appendLine("            planks.add(")
    sb.appendLine("                Plank(")
    sb.appendLine("                    id = \"p\${plankId++}\",")
    sb.appendLine("                    startRow = r1,")
    sb.appendLine("                    startCol = c1,")
    sb.appendLine("                    endRow = r2,")
    sb.appendLine("                    endCol = c2,")
    sb.appendLine("                    boltIds = attachedBolts,")
    sb.appendLine("                    depthLayer = p % 3")
    sb.appendLine("                )")
    sb.appendLine("            )")
    sb.appendLine("        }")
    sb.appendLine("        ")
    sb.appendLine("        return PregeneratedWoodNutsLevel(")
    sb.appendLine("            id = id,")
    sb.appendLine("            difficulty = difficulty,")
    sb.appendLine("            rows = size,")
    sb.appendLine("            cols = size,")
    sb.appendLine("            bolts = bolts,")
    sb.appendLine("            planks = planks,")
    sb.appendLine("            boardQueue = boardQueue")
    sb.appendLine("        )")
    sb.appendLine("    }")
    sb.appendLine("}")

    targetFile.parentFile.mkdirs()
    targetFile.writeText(sb.toString())
    println("Successfully generated Wood Nuts plank hole patterns into ${targetFile.path}")
}

fun main() {
    main(emptyArray())
}
