import os
import random

# Color Palette mapping for Cube Shooter
# 0: CYAN (C)
# 1: MAGENTA (M)
# 2: YELLOW (Y)
# 3: GREEN (G)
# 4: ORANGE (O)
# 5: PURPLE (P)
# 6: RED (R)
# 7: BLUE (B)
# 8: TEAL (T)
# 9: PINK (K)
# 10: INDIGO (I)
# 11: LIME (L)
# '.' or ' ': Empty / null

CHAR_TO_COLOR = {
    'C': 0, 'M': 1, 'Y': 2, 'G': 3, 'O': 4,
    'P': 5, 'R': 6, 'B': 7, 'T': 8, 'K': 9,
    'I': 10, 'L': 11
}

def parse_art(art_lines, target_cols, target_rows):
    lines = [line.rstrip('\r\n') for line in art_lines if line.strip() != '']
    rows = len(lines)
    cols = max(len(l) for l in lines) if lines else 0
    
    # Grid initialization
    grid = [[None for _ in range(target_cols)] for _ in range(target_rows)]
    
    row_offset = max(0, (target_rows - rows) // 2)
    col_offset = max(0, (target_cols - cols) // 2)
    
    for r in range(min(rows, target_rows)):
        line = lines[r]
        for c in range(min(len(line), target_cols)):
            char = line[c]
            if char in CHAR_TO_COLOR:
                grid[r + row_offset][c + col_offset] = CHAR_TO_COLOR[char]
                
    return grid

# --- EASY 15x15 LEVELS (15 levels) ---

EASY_ART = [
    # 1. Pixel Heart
    ("Cute Heart", """
...............
..RRR...RRR....
.RRRRR.RRRRR...
.RRRRRRRRRRR...
.RRRRRRRRRRR...
..RRRRRRRRR....
...RRRRRRR.....
....RRRRR......
.....RRR.......
......R........
...............
...............
...............
...............
...............
"""),
    # 2. Golden Star
    ("Golden Star", """
.......Y.......
......YYY......
.....YYYYY.....
.YYYYYYYYYYYYY.
..YYYYYYYYYYY..
...YYYYYYYYY...
....YYYYYYY....
...YYYY.YYYY...
..YYYY...YYYY..
.YYY.......YYY.
...............
...............
...............
...............
...............
"""),
    # 3. Super Mushroom
    ("Super Mushroom", """
.....RRRRR.....
...RRRRRRRRR...
..RRCCCCCRRRR..
.RRRCCCCCRRRRR.
.RRRRRRRRRRRRR.
.RRCCCCCRRRRRR.
..RRCCCCCRRRR..
...YYYYYYYYY...
...YYYYYYYYY...
...YYYYYYYYY...
....YYYYYYY....
...............
...............
...............
...............
"""),
    # 4. Sweet Cherries
    ("Sweet Cherries", """
.......GGG.....
......G...G....
.....G.....G...
....G.......G..
...G.........G.
..RRR.......RRR
.RRRRR.....RRRRR
.RRRRR.....RRRRR
.RRRRR.....RRRRR
..RRR.......RRR
...............
...............
...............
...............
...............
"""),
    # 5. Hero's Sword
    ("Hero's Sword", """
.........CC....
........CCCC...
.......CCCC....
......CCCC.....
.....CCCC......
....CCCC.......
...CCCC........
..YYYY.........
.YRRRY.........
.YYYY..........
...............
...............
...............
...............
...............
"""),
    # 6. Knight Shield
    ("Knight Shield", """
.YYYYYYYYYYYYY.
.YBBBBBRBBBBB.Y.
.YBBBBBRBBBBB.Y.
.YRRRRRRRRRRR.Y.
.YBBBBBRBBBBB.Y.
.YBBBBBRBBBBB.Y.
..YBBBBBRBBBY..
...YBBBBRBBY...
....YBBBRBY....
.....YBRBY.....
......YRY......
.......Y.......
...............
...............
...............
"""),
    # 7. Royal Crown
    ("Royal Crown", """
.Y.....Y.....Y.
.YY...YYY...YY.
.YYY.YYYYY.YYY.
.YYYYTTTTYYYYY.
.YYTTTTTTTTYYY.
.YYMMMMMMMMMYY.
.YYYYYYYYYYYYY.
.YYYYYYYYYYYYY.
...............
...............
...............
...............
...............
...............
...............
"""),
    # 8. Rubber Duckie
    ("Rubber Duckie", """
....YYYY.......
...YYYYYY......
..YYYYBCY.OO...
..YYYYYYY.OOO..
...YYYYYY......
...YYYYYYY.....
..YYYYYYYYY....
.YYYYYYYYYYY...
.YYYYYYYYYYY...
..YYYYYYYYY....
...............
...............
...............
...............
...............
"""),
    # 9. Cute Ghost
    ("Cute Ghost", """
....MMMMM......
..MMMMMMMMM....
.MMMMMMMMMMM...
.MMCCMMMCCMM...
.MMCCMMMCCMM...
.MMMMMMMMMMM...
.MMMMMMMMMMM...
.MMMMMMMMMMM...
.MM.MM.MM.MM...
...............
...............
...............
...............
...............
...............
"""),
    # 10. Chubby Penguin
    ("Chubby Penguin", """
....IIIII......
...IIIIIII.....
..IIICCIIII....
..IIIOOIIII....
..CCCCCCCCC....
.CCCCCCCCCCC...
.CCCCCCCCCCC...
.CCCCCCCCCCC...
..CCCCCCCCC....
...OOOOOOO.....
...............
...............
...............
...............
...............
"""),
    # 11. Red Apple
    ("Red Apple", """
......G........
.....GGG.......
......O........
..RRRR.RRRR....
.RRRRRRRRRRR...
.RRRRRRRRRRR...
.RRRRRRRRRRR...
.RRRRRRRRRRR...
..RRRRRRRRR....
...RRR.RRR.....
...............
...............
...............
...............
...............
"""),
    # 12. Desert Cactus
    ("Desert Cactus", """
...G.....G.....
...G.....G.....
...GGGGGGG.....
.....G.........
.....G.........
...OOOOO.......
...OOOOO.......
...OOOOO.......
....OOO........
...............
...............
...............
...............
...............
...............
"""),
    # 13. Nautical Anchor
    ("Nautical Anchor", """
......TTT......
.....T...T.....
......TTT......
.......T.......
....TTTTTTT....
.......T.......
.T.....T.....T.
.T.....T.....T.
..T...TTT...T..
...TTTTTTTTT...
...............
...............
...............
...............
...............
"""),
    # 14. Pixel Skull
    ("Pixel Skull", """
...PPPPPPP.....
..PPPPPPPPP....
.PPPPPPPPPPP...
.PP.PP.PP.PP...
.PP.PP.PP.PP...
.PPPPPPPPPPP...
..PPPPPPPPP....
...P.P.P.P.....
...P.P.P.P.....
...............
...............
...............
...............
...............
...............
"""),
    # 15. Magic Gem
    ("Magic Gem", """
.....CCCC......
...CCCCCCC.....
.CCCCCCCCCCCC..
.TTTTTTTTTTTT..
..TTTTTTTTTT...
...TTTTTTTT....
....TTTTTT.....
.....TTTT......
......TT.......
...............
...............
...............
...............
...............
...............
""")
]

# --- MEDIUM 20x20 LEVELS (15 levels) ---

MEDIUM_ART = [
    # 1. Orange Cat
    ("Orange Cat", """
.OOOO.......OOOO....
.OOOOO.....OOOOO....
.OOOOOO...OOOOOO....
.OOOOOOO.OOOOOOO....
.OOOOOOOOOOOOOOO....
.OOOGGOOOOOOGGOO....
.OOOGGOOOOOOGGOO....
.OOOOOOOKKOOOOOO....
.OOOOOOOOOOOOOOO....
..OOOOOOOOOOOOO.....
...OOOOOOOOOOO......
....OOOOOOOOO.......
....................
....................
....................
....................
....................
....................
....................
....................
"""),
    # 2. Playful Puppy
    ("Playful Puppy", """
..OOOO.....OOOO.....
.OOOOOO...OOOOOO....
.OOOOOOOOOOOOOOO....
.OOOOOOOOOOOOOOO....
.OOOBBOOOOOOBBOO....
.OOOBBOOOOOOBBOO....
.OOOOOOOKKOOOOOO....
.OOOOOOOKKOOOOOO....
..OOOOOOOOOOOOO.....
...OOOOOOOOOOO......
....IIIIIIIII.......
....................
....................
....................
....................
....................
....................
....................
....................
....................
"""),
    # 3. 8-Bit Plumber
    ("8-Bit Plumber", """
......RRRRR.........
.....RRRRRRRRR......
.....YYYYYYY........
....YYYBYYBYY.......
....YYYYYYYYY.......
.....YYYYYYY........
....RRRRRRRRR.......
...RRRRRRRRRRR......
..RRRRRRYRRRRRR.....
..RRRRRRYRRRRRR.....
..BBBBBBBBBBBBB.....
..BBBBBBBBBBBBB.....
..BBBBBBBBBBBBB.....
...YYYY...YYYY......
....................
....................
....................
....................
....................
....................
"""),
    # 4. Monster Ball
    ("Monster Ball", """
......RRRRRR........
....RRRRRRRRRR......
...RRRRRRRRRRRR.....
..RRRRRRRRRRRRRR....
.RRRRRRRRRRRRRRRR...
.RRRRRRRRRRRRRRRR...
.PPPPPPPPPPPPPPPP...
.PPPPPPCCCCPPPPPP...
.PPPPPPCCCCPPPPPP...
.CCCCCCCCCCCCCCCC...
.CCCCCCCCCCCCCCCC...
..CCCCCCCCCCCCCC....
...CCCCCCCCCCCC.....
....CCCCCCCCCC......
......CCCCCC........
....................
....................
....................
....................
....................
"""),
    # 5. Space Alien
    ("Space Alien", """
....LL.....LL.......
...LLLL...LLLL......
..LLLLLLLLLLLLLL....
..LLLL.LLLL.LLLL....
..LLLLLLLLLLLLLL....
....LLLLLLLLLL......
...LLLL....LLLL.....
..LLLL......LLLL....
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
"""),
    # 6. Game Pad
    ("Game Pad", """
.PPPPPPPPPPPPPPPPPP.
.PPPPPPPPPPPPPPPPPP.
.PP.Y..PP...M.C..PP.
.PYYYYYPP..MMMMCCPP.
.PP.Y..PP...M.C..PP.
.PPPPPPPPPPPPPPPPPP.
.PPPPPPPPPPPPPPPPPP.
..PPPPPPPPPPPPPPPP..
...PPPP......PPPP...
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
"""),
    # 7. Space Rocket
    ("Space Rocket", """
.........RR.........
........RRRR........
.......RRRRRR.......
......RRRRRRRR......
......RRCCCCRR......
......RRCCCCRR......
......RRRRRRRR......
......RRRRRRRR......
.....RRRRRRRRRR.....
....RRRRRRRRRRRR....
...OOOOOOOOOOOOOO...
...YYYYYYYYYYYYYY...
....................
....................
....................
....................
....................
....................
....................
....................
"""),
    # 8. Ringed Planet
    ("Ringed Planet", """
........MMMMM.......
......MMMMMMMMM.....
....CCCCCCMMMMMMM...
...CCCCMMMMMMMMM....
..CCCCMMMMMMMMMMM...
..CCCMMMMMMMMMMMM...
...CCMMMMMMMMMCCCC..
....MMMMMMMMCCCCCC..
......MMMMMMCCC.....
........MMMMM.......
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
"""),
    # 9. Cozy Cottage
    ("Cozy Cottage", """
.........RR.........
........RRRR........
.......RRRRRR.......
......RRRRRRRR......
.....RRRRRRRRRR.....
....RRRRRRRRRRRR....
...YYYYYYYYYYYYYY...
...YYYYCCYYCCYYYY...
...YYYYCCYYCCYYYY...
...YYYYYYYYYYYYYY...
...YYYYYYOOOOYYYY...
...YYYYYYOOOOYYYY...
...YYYYYYOOOOYYYY...
....................
....................
....................
....................
....................
....................
....................
"""),
    # 10. Red Speedster
    ("Red Speedster", """
........CCCCCC......
......CCCCCCCCCC....
....RRRRRRRRRRRRRR..
..RRRRRRRRRRRRRRRRRR
..RRRRRRRRRRRRRRRRRR
..RRIIIRRRRRRIIIRRRR
...RIIIFFFFFFIIIFFF.
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
"""),
    # 11. Monarch Butterfly
    ("Monarch Butterfly", """
.MMMM...YY...MMMM...
.MMMMM..YY..MMMMM...
.MMCCCC.YY.CCCCMM...
.MMCCCC.YY.CCCCMM...
..MMCCC.YY.CCCMM....
....MMM.YY.MMM......
...CCCC.YY.CCCC.....
..CCCCCCYYCCCCCC....
..CCCCCCYYCCCCCC....
...CCCC.YY.CCCC.....
....CC..YY..CC......
....................
....................
....................
....................
....................
....................
....................
....................
....................
"""),
    # 12. Bright Sunflower
    ("Bright Sunflower", """
.......YYYYY........
.....YYYYYYYYY......
....YYYYOOOOYYYY....
...YYYYOOOOOOYYYY...
...YYYYOOOOOOYYYY...
....YYYYOOOOYYYY....
.....YYYYYYYYY......
.......YYYYY........
.........GG.........
.........GG.........
.......GGGG.........
........GGG.........
.........GG.........
....................
....................
....................
....................
....................
....................
....................
"""),
    # 13. Victory Cup
    ("Victory Cup", """
.YYYYYYYYYYYYYYYYYY.
.YYYYYYYYYYYYYYYYYY.
.YY..YYYYCCCCYYYY..YY
.YY..YYYYCCCCYYYY..YY
..Y..YYYYYYYYYYYY..Y.
.....YYYYYYYYYYYY....
......YYYYYYYYYY.....
.......YYYYYYYY......
........YYYYYY.......
.........YYYY........
.........YYYY........
......PPPPPPPPPP.....
......PPPPPPPPPP.....
....................
....................
....................
....................
....................
....................
....................
"""),
    # 14. Glazed Donut
    ("Glazed Donut", """
......KKKKKKKK......
....KKKKKKKKKKKK....
...KKK.Y.C.M.KKKK...
..KKKKKKKKKKKKKKKK..
..KKKKKK....KKKKKK..
..KKKKKK....KKKKKK..
..KKKKKKKKKKKKKKKK..
...KKKK.Y.C.M.KKK...
....KKKKKKKKKKKK....
......KKKKKKKK......
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
"""),
    # 15. Pepperoni Pizza
    ("Pepperoni Pizza", """
.OOOOOOOOOOOOOOOOOO.
.YYYYYYYYYYYYYYYYYY.
..YYRRRYYYYYYRRRYY..
..YYRRRYYYYYYRRRYY..
...YYYYYYYYYYYYYY...
....YYYYYRRRYYYY....
....YYYYYRRRYYYY....
.....YYYYYYYYYY.....
......YYYYYYYY......
.......YYRRRYY......
.......YYRRRYY......
........YYYYY.......
.........YYY........
..........Y.........
....................
....................
....................
....................
....................
....................
""")
]

# --- HARD 30x30 LEVELS (15 levels) ---

HARD_ART = [
    # 1. Fire Dragon
    ("Fire Dragon", """
...................RRR........
..................RRRRR.......
................RRRRRRRR......
...............RRRRRRRRRR.....
..............RRRRRRRRRRRR....
.RR..........RRRR..RRRRRRRR...
.RRR........RRRR....RRRRRRRR..
.RRRR......RRRR......RRRRRRRR.
.RRRRR....RRRR........RRRRRRR.
.RRRRRR..RRRR..........RRRRRR.
.RRRRRRRRRRR............RRRRR.
..RRRRRRRRR...OOOOOO.....RRRR.
...RRRRRRR...OOOOOOOO.....RRR.
....RRRRR...OOOOOOOOOO.....RR.
.....RRR...YYYYYYYYYYYY.....R.
......R...YYYYYYYYYYYYYY......
.........YYYYYYYYYYYYYYYY.....
........YYYYYYYYYYYYYYYYYY....
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
"""),
    # 2. Royal Castle
    ("Royal Castle", """
.RR..............RR..............RR.
.RR..............RR..............RR.
.PP..............PP..............PP.
.PP..............PP..............PP.
.PPPPPP......PPPPPPPPPP......PPPPPP.
.PPPPPP......PPPPPPPPPP......PPPPPP.
.PPPPPP......PPPPPPPPPP......PPPPPP.
.PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP.
.PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP.
.PPPPYYPPPPPPPPYYPPPPYYYYPPPPYYPPPP.
.PPPPYYPPPPPPPPYYPPPPYYYYPPPPYYPPPP.
.PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP.
.PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP.
.PPPPPPPPPPPPPPPOOOPPPPPPPPPPPPPPPP.
.PPPPPPPPPPPPPOOOOOOOPPPPPPPPPPPPPP.
.PPPPPPPPPPPPPOOOOOOOPPPPPPPPPPPPPP.
.PPPPPPPPPPPPPOOOOOOOPPPPPPPPPPPPPP.
.PPPPPPPPPPPPPOOOOOOOPPPPPPPPPPPPPP.
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
"""),
    # 3. Fiery Phoenix
    ("Fiery Phoenix", """
..............RR..............
.............RRRR.............
............RRRRRR............
...........RRRRRRRR...........
.MM.......RRRRRRRRRR.......MM.
.MMM.....RRRRRRRRRRRR.....MMM.
.MMMM...RRRRRRRRRRRRRR...MMMM.
.MMMMM.RRRRRRRRRRRRRRRR.MMMMM.
.OOOOOOOOOOOOOOOOOOOOOOOOOOOO.
..OOOOOOOOOOOOOOOOOOOOOOOOOO..
...YYYYYYYYYYYYYYYYYYYYYYYY...
....YYYYYYYYYYYYYYYYYYYYYY....
.....YYYYYYYYYYYYYYYYYYYY.....
......YYYYYYYYYYYYYYYYYY......
.......YYYYYYYYYYYYYYYY.......
........YYYYYYYYYYYYYY........
.........YYYYYYYYYYYY.........
..........YYYYYYYYYY..........
...........YYYYYYYY...........
............YYYYYY............
.............YYYY.............
..............YY..............
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
"""),
    # 4. Pirate Galleon
    ("Pirate Galleon", """
...............RR.............
..............RRRR............
.............RRRRRR...........
............RRRRRRRR..........
...........CCCCCCCCCC.........
..........CCCCCCCCCCCC........
.........CCCCCCCCCCCCCC.......
........CCCCCCCCCCCCCCCC......
...............OO.............
...............OO.............
......OOOOOOOOOOOOOOOOOOOO....
.....OOOOOOOOOOOOOOOOOOOOOO...
....OOOOOOOOOOOOOOOOOOOOOOOO..
...OOOOOOOOOOOOOOOOOOOOOOOOOO.
..BBBBBBBBBBBBBBBBBBBBBBBBBBBB
.BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
.BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
"""),
    # 5. Arcane Wizard
    ("Arcane Wizard", """
...............BB.............
..............BBBB............
.............BBBBBB...........
............BBBBBBBB..........
...........BBBBYYYYBB.........
..........BBBBBBBBBBBB........
.........BBBBBBBBBBBBBB.......
........PPPPPPPPPPPPPPPP......
.......PPPPPPPPPPPPPPPPPP.....
......PPPPPPPPYYYYPPPPPPPP....
.....PPPPPPPPYYYYYYPPPPPPPP...
....PPPPPPPPPPPPPPPPPPPPPPPP..
...PPPPPPPPPPPPPPPPPPPPPPPPPP.
..PPPPPPPPPPPPPPPPPPPPPPPPPPPP
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
"""),
    # 6. Cyber Mech
    ("Cyber Mech", """
............CCCCCC............
...........CCCCCCCC...........
...........CCYYYYCC...........
...........CCCCCCCC...........
.........CCCCCCCCCCCC.........
........CCCCCCCCCCCCCC........
.......CCCCCCRRRRCCCCCC.......
......CCCCCCRRRRRRCCCCCC......
......CCCCCCRRRRRRCCCCCC......
......CCCCCCRRRRRRCCCCCC......
.......CCCCCCRRRRCCCCCC.......
........CCCCCCCCCCCCCC........
.........CCCC....CCCC.........
.........CCCC....CCCC.........
.........CCCC....CCCC.........
.........CCCC....CCCC.........
........CCCCCC..CCCCCC........
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
"""),
    # 7. Alpine Peak
    ("Alpine Peak", """
.......................YYYY...
......................YYYYYY..
.......................YYYY...
..............CC..............
.............CCCC.............
............CCCCCC............
...........CCCCCCCC...........
..........CCCCCCCCCC..........
.........GGGGGGGGGGGG.........
........GGGGGGGGGGGGGG........
.......GGGGGGGGGGGGGGGG.......
......GGGGGGGGGGGGGGGGGG......
.....GGGGGGGGGGGGGGGGGGGG.....
....GGGGGGGGGGGGGGGGGGGGGG....
...GGGGGGGGGGGGGGGGGGGGGGGG...
..GGGGGGGGGGGGGGGGGGGGGGGGGG..
.GGGGGGGGGGGGGGGGGGGGGGGGGGGG.
.GGGGGGGGGGGGGGGGGGGGGGGGGGGG.
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
"""),
    # 8. Wise Owl
    ("Wise Owl", """
...........OOOOOOOO...........
..........OOOOOOOOOO..........
.........OOOOOOOOOOOO.........
........OOOOYYYYOOOOOO........
.......OOOOYYYYYYOOOOOO.......
.......OOOOYYGGYYOOOOOO.......
.......OOOOYYGGYYOOOOOO.......
........OOOOYYYYOOOOOO........
.........OOOOOOOOOOOO.........
..........OOOOOOOOOO..........
..........OOOOOOOOOO..........
..........OOOOOOOOOO..........
.........GGGGGGGGGGGG.........
........GGGGGGGGGGGGGG........
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
"""),
    # 9. Mystic Unicorn
    ("Mystic Unicorn", """
...................YY.........
..................YYYY........
.................CCCCCC.......
................CCCCCCCC......
..MMMM.........CCCCCCCCCC.....
.MMMMMM.......CCCC.CCC.CCC....
.MMMMMMM.....CCCCCCC.CCCCCC...
.MMMMMMMM...CCCCCCCCCCCCCCC...
..MMMMMMMM.CCCCCCCCCCCCCCCC...
...MMMMMMMMCCCCCCCCCCCCCCCC...
....MMMMMMMMCCCCCCCCCCCC......
.....MMMMMMMMCCCCCCC..........
......MMMMMMMMCCCC............
.......MMMMMMMM...............
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
"""),
    # 10. Neon Oni Mask
    ("Neon Oni Mask", """
.TT........................TT.
.TTT......................TTT.
.TTTT....................TTTT.
.TTTTT..................TTTTT.
..TTTTTT..............TTTTTT..
...TTTTTTTTMMMMMMMMTTTTTTTT...
....TTTTTTMMMMMMMMMMTTTTTT....
.....TTTTMMMMMMMMMMMMTTTT.....
......TTMMMMTTTTTTMMMMTT......
......TTMMMMTTTTTTMMMMTT......
.......MMMMMMMMMMMMMMMM.......
.......MMMMMMTTTTMMMMMM.......
........MMMMMTTTTMMMMM........
.........MMMMMMMMMMMM.........
..........MMMMMMMMMM..........
...........MMMMMMMM...........
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
"""),
    # 11. Rock Guitar
    ("Rock Guitar", """
..........................RR..
.........................RRRR.
........................RRRR..
.......................TT.....
......................TT......
.....................TT.......
....................TT........
...................TT.........
..................TT..........
.................TT...........
........RRRRRRRRTT............
......RRRRRRRRRRRR............
.....RRRRRRRYYRRRRR...........
....RRRRRRRRYYRRRRRR..........
...RRRRRRRRRRRRRRRRRR.........
...RRRRRRRRRRRRRRRRRR.........
...RRRRRRRRRRRRRRRRRR.........
....RRRRRRRRRRRRRRRR..........
......RRRRRRRRRRRR............
........RRRRRRRR..............
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
"""),
    # 12. Tropical Sunset
    ("Tropical Sunset", """
.PPPPPPPPPPPPPPPPPPPPPPPPPPPP.
.PPPPPPPPPPPPPPPPPPPPPPPPPPPP.
.MMMMMMMMMMMMMMMMMMMMMMMMMMMM.
.MMMMMMMMMMMMMMMMMMMMMMMMMMMM.
.OOOOOOOOOOOOOOOOOOOOOOOOOOOO.
.OOOOOOOOOOOOOOOOOOOOOOOOOOOO.
.YYYYYYYYYYYYYYYYYYYYYYYYYYYY.
.YYYYYYYYYYYYYYYYYYYYYYYYYYYY.
.TTTTTTTTTTTTTTTTTTTTTTTTTTTT.
.TTTTTTTTTTTTTTTTTTTTTTTTTTTT.
.TTTTTTTTTTTTTTTTTTTTTTTTTTTT.
.TTTTTTTTTTTTTTTTTTTTTTTTTTTT.
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
"""),
    # 13. Bengal Tiger
    ("Bengal Tiger", """
.OOOO...............OOOO......
.OOOOO.............OOOOO......
.OOOOOO...........OOOOOO......
.OOOOOOO.........OOOOOOO......
.OOOOOOOOOOOOOOOOOOOOOOO......
.OOOOIIIOOOOOOOOOIIIOOOO......
.OOOOIIIOOOOOOOOOIIIOOOO......
.OOOOOOOGGOOOOOOGGOOOOOO......
.OOOOOOOGGOOOOOOGGOOOOOO......
.OOOOOOOOOIIIIIIOOOOOOOO......
.OOOOOOOOOOOOOOOOOOOOOOO......
..OOOOOOOOIIIIIIOOOOOOO.......
...OOOOOOOOOOOOOOOOOOO........
....OOOOOOOOOOOOOOOO..........
.....OOOOOOOOOOOOOO...........
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
"""),
    # 14. Soaring Eagle
    ("Soaring Eagle", """
.............CCCC.............
............CCCCCC............
...........CCCCCCCC...........
..........CCCCCCCCCC..........
.OOOO....CCCCCCCCCCCC....OOOO.
.OOOOO..CCCCCCCCCCCCCC..OOOOO.
.OOOOOO.CCCCCCCCCCCCCC.OOOOOO.
.OOOOOOO.CCCCCCCCCCCC.OOOOOOO.
.OOOOOOOO.CCCCCCCCCC.OOOOOOOO.
.OOOOOOOOO.CCCCCCCC.OOOOOOOOO.
..OOOOOOOOO.CCCCCC.OOOOOOOOO..
...OOOOOOOOO.CCCC.OOOOOOOOO...
....OOOOOOOOO.CC.OOOOOOOOO....
.....OOOOOOOO....OOOOOOOO.....
......OOOOOO......OOOOOO......
.......OOOO........OOOO.......
........OO..........OO........
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
"""),
    # 15. Treasure Chest
    ("Treasure Chest", """
.......CCCC.RRRR.YYYY.........
......CCCC.RRRR.YYYY..........
.....OOOOOOOOOOOOOOOOOO.......
....OOOOOOOOOOOOOOOOOOOO......
...OOOOOOOOOOOOOOOOOOOOOO.....
..YYYYYYYYYYYYYYYYYYYYYYYY....
..YYYYYYYCCCCCCCCYYYYYYYYY....
..YYYYYYYCCCCCCCCYYYYYYYYY....
..OOOOOOOOOOOOOOOOOOOOOOOO....
..OOOOOOOOOOOOOOOOOOOOOOOO....
..OOOOOOOYYYYYYYYYOOOOOOOO....
..OOOOOOOYYYYYYYYYOOOOOOOO....
..OOOOOOOOOOOOOOOOOOOOOOOO....
..OOOOOOOOOOOOOOOOOOOOOOOO....
...OOOOOOOOOOOOOOOOOOOOOO.....
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
""")
]

def build_tray_str(grid_matrix, seed_offset):
    # Count occurrences of each color
    counts = {}
    for r in grid_matrix:
        for cell in r:
            if cell is not None:
                counts[cell] = counts.get(cell, 0) + 1
                
    rand = random.Random(20240801 + seed_offset)
    tanks = []
    
    for color in sorted(counts.keys()):
        rem = counts[color]
        while rem > 0:
            ammo = min(rem, 20 if rem >= 20 else 15 if rem >= 15 else 10 if rem >= 10 else 5 if rem >= 5 else rem)
            tanks.append((color, ammo))
            rem -= ammo
            
    rand.shuffle(tanks)
    return ";".join(f"{c},{a}" for c, a in tanks)

def grid_to_str(grid_matrix):
    rows = []
    for r in grid_matrix:
        row_str = ",".join(str(cell) if cell is not None else "" for cell in r)
        rows.append(row_str)
    return "|".join(rows)

def generate_files():
    all_levels_meta = [] # (id, name, diff, cols, rows, grid_str, tray_str, chunk_name)
    
    idx = 1
    # Easy
    for name, art in EASY_ART:
        g = parse_art(art.split('\n'), 15, 15)
        grid_s = grid_to_str(g)
        tray_s = build_tray_str(g, idx)
        chunk = f"CHUNK_EASY_{idx}"
        level_id = f"cubeshooter_easy_{idx:03d}"
        all_levels_meta.append((level_id, name, "Easy", 15, 15, grid_s, tray_s, chunk))
        idx += 1
        
    idx = 1
    # Medium
    for name, art in MEDIUM_ART:
        g = parse_art(art.split('\n'), 20, 20)
        grid_s = grid_to_str(g)
        tray_s = build_tray_str(g, idx + 100)
        chunk = f"CHUNK_MEDIUM_{idx}"
        level_id = f"cubeshooter_medium_{idx:03d}"
        all_levels_meta.append((level_id, name, "Medium", 20, 20, grid_s, tray_s, chunk))
        idx += 1
        
    idx = 1
    # Hard
    for name, art in HARD_ART:
        g = parse_art(art.split('\n'), 30, 30)
        grid_s = grid_to_str(g)
        tray_s = build_tray_str(g, idx + 200)
        chunk = f"CHUNK_HARD_{idx}"
        level_id = f"cubeshooter_hard_{idx:03d}"
        all_levels_meta.append((level_id, name, "Hard", 30, 30, grid_s, tray_s, chunk))
        idx += 1

    # Generate CubeShooterPregenerated.kt
    sb = []
    sb.append("package com.funkyotc.puzzleverse.cubeshooter.data")
    sb.append("")
    sb.append("import com.funkyotc.puzzleverse.core.data.BrowseablePuzzle")
    sb.append("")
    sb.append("data class PregeneratedLevel(")
    sb.append("    override val id: String,")
    sb.append("    val name: String,")
    sb.append("    override val difficulty: String,")
    sb.append("    val cols: Int,")
    sb.append("    val rows: Int,")
    sb.append("    val grid: List<List<Int?>>,")
    sb.append("    val tray: List<Tank>")
    sb.append(") : BrowseablePuzzle {")
    sb.append("    override val label: String get() = name")
    sb.append("    override val subtitle: String get() = \"${cols}x${rows}\"")
    sb.append("}")
    sb.append("")
    sb.append("object CubeShooterPregenerated {")
    sb.append("")
    sb.append("    private fun parseLevel(")
    sb.append("        id: String, name: String, difficulty: String, cols: Int, rows: Int,")
    sb.append("        grid: String, tray: String")
    sb.append("    ): PregeneratedLevel {")
    sb.append("        val parsedGrid = grid.split('|').map { row ->")
    sb.append("            row.split(',').map { it.toIntOrNull() }")
    sb.append("        }")
    sb.append("        val parsedTray = tray.split(';').map { part ->")
    sb.append("            val (c, a) = part.split(',').map { it.toInt() }")
    sb.append("            Tank(c, a)")
    sb.append("        }")
    sb.append("        return PregeneratedLevel(id, name, difficulty, cols, rows, parsedGrid, parsedTray)")
    sb.append("    }")
    sb.append("")
    
    chunk_names = []
    for lid, name, diff, cols, rows, grid_s, tray_s, chunk in all_levels_meta:
        chunk_names.append(chunk)
        sb.append(f"    private val {chunk} by lazy {{")
        sb.append("        parseLevel(")
        sb.append(f'            "{lid}", "{name}", "{diff}", {cols}, {rows},')
        sb.append(f'            grid = "{grid_s}",')
        sb.append(f'            tray = "{tray_s}"')
        sb.append("        )")
        sb.append("    }")
        sb.append("")
        
    sb.append("    val ALL_LEVELS: List<PregeneratedLevel> by lazy {")
    sb.append(f"        listOf({', '.join(chunk_names)})")
    sb.append("    }")
    sb.append("")
    sb.append("    val LEVELS_BY_DIFFICULTY: Map<String, List<PregeneratedLevel>> by lazy { ALL_LEVELS.groupBy { it.difficulty } }")
    sb.append("}")

    target_kt = "app/src/main/java/com/funkyotc/puzzleverse/cubeshooter/data/CubeShooterPregenerated.kt"
    os.makedirs(os.path.dirname(target_kt), exist_ok=True)
    with open(target_kt, "w", encoding="utf-8") as f:
        f.write("\n".join(sb))
        
    print(f"Successfully generated {len(all_levels_meta)} levels into {target_kt}")

if __name__ == "__main__":
    generate_files()
