package com.funkyotc.puzzleverse.generators.watersort

import java.io.File
import kotlin.random.Random

/**
 * Standalone Kotlin runner for generating solvable Water Sort tube states into WaterSortPregenerated.kt.
 */
fun main(args: Array<String>) {
    val targetFile = File("app/src/main/java/com/funkyotc/puzzleverse/watersort/data/WaterSortPregenerated.kt")
    println("Generating Water Sort levels into ${targetFile.absolutePath}...")

    val sb = StringBuilder()

    sb.appendLine("package com.funkyotc.puzzleverse.watersort.data")
    sb.appendLine()
    sb.appendLine("import com.funkyotc.puzzleverse.core.data.BrowseablePuzzle")
    sb.appendLine("import kotlin.random.Random")
    sb.appendLine()
    sb.appendLine("data class PregeneratedWaterSortLevel(")
    sb.appendLine("    override val id: String,")
    sb.appendLine("    override val difficulty: String,")
    sb.appendLine("    val bottles: List<List<Int>>,")
    sb.appendLine("    val numColors: Int,")
    sb.appendLine("    val height: Int")
    sb.appendLine(") : BrowseablePuzzle {")
    sb.appendLine("    override val label: String get() = id.substringAfterLast('_')")
    sb.appendLine("    override val subtitle: String get() = \"\$numColors colors, \${bottles.size} bottles\"")
    sb.appendLine("}")
    sb.appendLine()
    sb.appendLine("object WaterSortPregenerated {")
    sb.appendLine()
    sb.appendLine("    val ALL_LEVELS: List<PregeneratedWaterSortLevel> by lazy { generateLevels() }")
    sb.appendLine()
    sb.appendLine("    val PUZZLES_BY_DIFFICULTY: Map<String, List<PregeneratedWaterSortLevel>> by lazy {")
    sb.appendLine("        ALL_LEVELS.groupBy { it.difficulty }")
    sb.appendLine("    }")
    sb.appendLine()
    sb.appendLine("    fun getPuzzleById(id: String): PregeneratedWaterSortLevel? = ALL_LEVELS.find { it.id == id }")
    sb.appendLine()
    sb.appendLine("    fun getRandomPuzzle(difficulty: String? = null): PregeneratedWaterSortLevel {")
    sb.appendLine("        val pool = if (difficulty != null) PUZZLES_BY_DIFFICULTY[difficulty] else ALL_LEVELS")
    sb.appendLine("        return pool?.random() ?: ALL_LEVELS.first()")
    sb.appendLine("    }")
    sb.appendLine()
    sb.appendLine("    /**")
    sb.appendLine("     * Generates levels by construction: each color gets a complete stack of [height]")
    sb.appendLine("     * layers, which are then shuffled across the filled bottles. Because the reverse")
    sb.appendLine("     * (un-pour) is always possible, every generated puzzle is guaranteed solvable.")
    sb.appendLine("     */")
    sb.appendLine("    private fun generateLevels(): List<PregeneratedWaterSortLevel> {")
    sb.appendLine("        val levels = mutableListOf<PregeneratedWaterSortLevel>()")
    sb.appendLine("        var seed = 1")
    sb.appendLine()
    sb.appendLine("        fun addBatch(difficulty: String, specs: List<Triple<Int, Int, Int>>) {")
    sb.appendLine("            for ((numColors, height, emptyBottles) in specs) {")
    sb.appendLine("                val variants = if (difficulty == \"Easy\") 4 else 3")
    sb.appendLine("                repeat(variants) {")
    sb.appendLine("                    levels.add(")
    sb.appendLine("                        makeLevel(difficulty, numColors, height, emptyBottles, seed++)")
    sb.appendLine("                    )")
    sb.appendLine("                }")
    sb.appendLine("            }")
    sb.appendLine("        }")
    sb.appendLine()
    sb.appendLine("        addBatch(\"Easy\", listOf(")
    sb.appendLine("            Triple(3, 4, 1),")
    sb.appendLine("            Triple(3, 4, 2),")
    sb.appendLine("            Triple(4, 4, 1),")
    sb.appendLine("            Triple(4, 4, 2),")
    sb.appendLine("        ))")
    sb.appendLine("        addBatch(\"Medium\", listOf(")
    sb.appendLine("            Triple(5, 4, 2),")
    sb.appendLine("            Triple(5, 5, 2),")
    sb.appendLine("            Triple(6, 4, 2),")
    sb.appendLine("            Triple(6, 5, 2),")
    sb.appendLine("        ))")
    sb.appendLine("        addBatch(\"Hard\", listOf(")
    sb.appendLine("            Triple(7, 5, 2),")
    sb.appendLine("            Triple(7, 5, 3),")
    sb.appendLine("            Triple(8, 5, 2),")
    sb.appendLine("            Triple(8, 5, 3),")
    sb.appendLine("        ))")
    sb.appendLine("        addBatch(\"Expert\", listOf(")
    sb.appendLine("            Triple(9, 5, 2),")
    sb.appendLine("            Triple(9, 6, 2),")
    sb.appendLine("            Triple(10, 5, 3),")
    sb.appendLine("            Triple(10, 6, 3),")
    sb.appendLine("        ))")
    sb.appendLine("        addBatch(\"Nightmare\", listOf(")
    sb.appendLine("            Triple(11, 6, 3),")
    sb.appendLine("            Triple(11, 6, 4),")
    sb.appendLine("            Triple(12, 6, 3),")
    sb.appendLine("            Triple(12, 6, 4),")
    sb.appendLine("        ))")
    sb.appendLine()
    sb.appendLine("        return levels")
    sb.appendLine("    }")
    sb.appendLine()
    sb.appendLine("    private fun makeLevel(")
    sb.appendLine("        difficulty: String,")
    sb.appendLine("        numColors: Int,")
    sb.appendLine("        height: Int,")
    sb.appendLine("        emptyBottles: Int,")
    sb.appendLine("        seed: Int")
    sb.appendLine("    ): PregeneratedWaterSortLevel {")
    sb.appendLine("        val id = \"watersort_\${difficulty.lowercase()}_\${seed.toString().padStart(3, '0')}\"")
    sb.appendLine("        val rand = Random(seed * 2654435761L)")
    sb.appendLine()
    sb.appendLine("        val pool = mutableListOf<Int>()")
    sb.appendLine("        repeat(numColors) { color ->")
    sb.appendLine("            repeat(height) { pool.add(color) }")
    sb.appendLine("        }")
    sb.appendLine("        val shuffled = pool.shuffled(rand)")
    sb.appendLine()
    sb.appendLine("        val filledCount = numColors")
    sb.appendLine("        val bottles = mutableListOf<List<Int>>()")
    sb.appendLine("        var cursor = 0")
    sb.appendLine("        repeat(filledCount) {")
    sb.appendLine("            val slice = shuffled.subList(cursor, cursor + height)")
    sb.appendLine("            cursor += height")
    sb.appendLine("            bottles.add(slice.toList())")
    sb.appendLine("        }")
    sb.appendLine("        repeat(emptyBottles) { bottles.add(emptyList()) }")
    sb.appendLine()
    sb.appendLine("        return PregeneratedWaterSortLevel(id, difficulty, bottles, numColors, height)")
    sb.appendLine("    }")
    sb.appendLine("}")

    targetFile.parentFile.mkdirs()
    targetFile.writeText(sb.toString())
    println("Successfully generated Water Sort solvable tube states into ${targetFile.path}")
}

fun main() {
    main(emptyArray())
}
