package com.funkyotc.puzzleverse.generators.pullpin

import java.io.File
import kotlin.random.Random

/**
 * Standalone Kotlin runner for generating Pull Pin physics layout definitions into PullPinPregenerated.kt.
 */
fun main(args: Array<String>) {
    val targetFile = File("app/src/main/java/com/funkyotc/puzzleverse/pullpin/data/PullPinPregenerated.kt")
    println("Generating Pull Pin levels into ${targetFile.absolutePath}...")

    val sb = StringBuilder()

    sb.appendLine("package com.funkyotc.puzzleverse.pullpin.data")
    sb.appendLine()
    sb.appendLine("import kotlin.random.Random")
    sb.appendLine()
    sb.appendLine("private val COMMON_WALLS = listOf(")
    sb.appendLine("    WallSegment(0f, 680f, 400f, 20f),   // floor")
    sb.appendLine("    WallSegment(0f, 0f, 12f, 700f),     // left")
    sb.appendLine("    WallSegment(388f, 0f, 12f, 700f),   // right")
    sb.appendLine("    WallSegment(0f, 0f, 400f, 12f)      // top")
    sb.appendLine(")")
    sb.appendLine()
    sb.appendLine("private fun makeLevel(id: String, difficulty: String, cupCount: Int, extraGrey: Boolean): PullPinLevel {")
    sb.appendLine("    val rng = Random(id.hashCode().toLong())")
    sb.appendLine("    val walls = COMMON_WALLS.toMutableList()")
    sb.appendLine("    val cups = mutableListOf<CupData>()")
    sb.appendLine("    val pins = mutableListOf<PinData>()")
    sb.appendLine("    val balls = mutableListOf<BallSpawn>()")
    sb.appendLine()
    sb.appendLine("    val left = 12f")
    sb.appendLine("    val right = 388f")
    sb.appendLine("    val interior = right - left")
    sb.appendLine("    val cupY = 658f")
    sb.appendLine("    val cupRadius = 22f")
    sb.appendLine()
    sb.appendLine("    for (i in 0 until cupCount) {")
    sb.appendLine("        val frac = (i + 0.5f) / cupCount.toFloat()")
    sb.appendLine("        val cx = left + interior * frac")
    sb.appendLine("        val color = (i % 8) + 1")
    sb.appendLine()
    sb.appendLine("        // divider wall between adjacent cup columns")
    sb.appendLine("        if (i < cupCount - 1) {")
    sb.appendLine("            val nextFrac = (i + 1.5f) / cupCount.toFloat()")
    sb.appendLine("            val nextCx = left + interior * nextFrac")
    sb.appendLine("            val midX = (cx + nextCx) / 2f")
    sb.appendLine("            walls.add(WallSegment(midX - 6f, 300f, 12f, 355f))")
    sb.appendLine("        }")
    sb.appendLine()
    sb.appendLine("        cups.add(CupData(\"cup_\$i\", cx, cupY, cupRadius, color))")
    sb.appendLine()
    sb.appendLine("        // colored ball directly above its cup, resting on a holding pin")
    sb.appendLine("        balls.add(BallSpawn(\"ball_\$i\", cx, 600f, color, 16f))")
    sb.appendLine("        val pullDx = if (i % 2 == 0) 1f else -1f")
    sb.appendLine("        pins.add(PinData(\"pin_\$i\", cx - 40f, 620f, 80f, 10f, pullDx, 0f, false, false))")
    sb.appendLine()
    sb.appendLine("        if (extraGrey) {")
    sb.appendLine("            // grey ball above, held by a second pin (colored on contact)")
    sb.appendLine("            balls.add(BallSpawn(\"ball_\${i}_g\", cx, 500f, 0, 16f))")
    sb.appendLine("            pins.add(PinData(\"pin_\${i}_g\", cx - 40f, 540f, 80f, 10f, pullDx, 0f, false, false))")
    sb.appendLine("        }")
    sb.appendLine("    }")
    sb.appendLine()
    sb.appendLine("    return PullPinLevel(id, difficulty, walls, cups, pins, balls)")
    sb.appendLine("}")
    sb.appendLine()
    sb.appendLine("private fun levelsFor(difficulty: String, count: Int, cupCount: Int, extraGrey: Boolean): List<PullPinLevel> {")
    sb.appendLine("    return List(count) { idx ->")
    sb.appendLine("        val id = \"pullpin_\${difficulty.lowercase()}_\${(idx + 1).toString().padStart(3, '0')}\"")
    sb.appendLine("        makeLevel(id, difficulty, cupCount, extraGrey)")
    sb.appendLine("    }")
    sb.appendLine("}")
    sb.appendLine()
    sb.appendLine("object PullPinPregenerated {")
    sb.appendLine("    val ALL_LEVELS: List<PullPinLevel> = buildList {")
    sb.appendLine("        addAll(levelsFor(\"Easy\", 12, 2, false))")
    sb.appendLine("        addAll(levelsFor(\"Medium\", 12, 3, false))")
    sb.appendLine("        addAll(levelsFor(\"Hard\", 12, 4, true))")
    sb.appendLine("        addAll(levelsFor(\"Expert\", 12, 5, true))")
    sb.appendLine("    }")
    sb.appendLine()
    sb.appendLine("    val PUZZLES_BY_DIFFICULTY: Map<String, List<PullPinLevel>> = ALL_LEVELS.groupBy { it.difficulty }")
    sb.appendLine("}")

    targetFile.parentFile.mkdirs()
    targetFile.writeText(sb.toString())
    println("Successfully generated Pull Pin layout definitions into ${targetFile.path}")
}

fun main() {
    main(emptyArray())
}
