package generators.pullpin

import java.io.File
import kotlin.random.Random

/**
 * Standalone Kotlin runner for generating Pull Pin physics layout definitions into PullPinPregenerated.kt.
 */
fun main(args: Array<String>) {
    val targetFileCandidates = listOf(
        File("app/src/main/java/com/funkyotc/puzzleverse/pullpin/data/PullPinPregenerated.kt"),
        File("C:/Users/funky/AppDev/PuzzleVerse/app/src/main/java/com/funkyotc/puzzleverse/pullpin/data/PullPinPregenerated.kt")
    )
    val targetFile = targetFileCandidates.find { it.parentFile?.exists() == true } ?: targetFileCandidates.first()
    println("Generating Pull Pin levels into ${targetFile.absolutePath}...")

    val sb = StringBuilder()

    sb.appendLine("package com.funkyotc.puzzleverse.pullpin.data")
    sb.appendLine()
    sb.appendLine("import kotlin.random.Random")
    sb.appendLine()
    sb.appendLine("private val COMMON_WALLS = listOf(")
    sb.appendLine("    WallSegment(0f, 680f, 400f, 20f),   // floor")
    sb.appendLine("    WallSegment(0f, 0f, 12f, 700f),     // left")
    sb.appendLine("    WallSegment(388f, 0f, 12f, 700f),   // right")
    sb.appendLine("    WallSegment(0f, 0f, 400f, 12f)      // top")
    sb.appendLine(")")
    sb.appendLine()
    sb.appendLine("private fun makeLevel(id: String, difficulty: String, idx: Int): PullPinLevel {")
    sb.appendLine("    val rng = Random(id.hashCode().toLong())")
    sb.appendLine("    val walls = COMMON_WALLS.toMutableList()")
    sb.appendLine("    val cups = mutableListOf<CupData>()")
    sb.appendLine("    val pins = mutableListOf<PinData>()")
    sb.appendLine("    val balls = mutableListOf<BallSpawn>()")
    sb.appendLine()
    sb.appendLine("    val left = 12f")
    sb.appendLine("    val right = 388f")
    sb.appendLine("    val interior = right - left")
    sb.appendLine("    val cupY = 658f")
    sb.appendLine("    val cupRadius = 22f")
    sb.appendLine()
    sb.appendLine("    val cupCount = when (difficulty) {")
    sb.appendLine("        \"Easy\" -> 2")
    sb.appendLine("        \"Medium\" -> 3")
    sb.appendLine("        \"Hard\" -> 4")
    sb.appendLine("        else -> 5")
    sb.appendLine("    }")
    sb.appendLine("    val hasGrey = difficulty == \"Hard\" || difficulty == \"Expert\" || idx % 2 == 1")
    sb.appendLine()
    sb.appendLine("    for (i in 0 until cupCount) {")
    sb.appendLine("        val frac = (i + 0.5f) / cupCount.toFloat()")
    sb.appendLine("        val cx = left + interior * frac")
    sb.appendLine("        val color = (i % 8) + 1")
    sb.appendLine()
    sb.appendLine("        // Dividers between cups")
    sb.appendLine("        if (i < cupCount - 1) {")
    sb.appendLine("            val nextFrac = (i + 1.5f) / cupCount.toFloat()")
    sb.appendLine("            val nextCx = left + interior * nextFrac")
    sb.appendLine("            val midX = (cx + nextCx) / 2f")
    sb.appendLine("            val dividerH = if (idx % 3 == 0) 380f else 320f")
    sb.appendLine("            walls.add(WallSegment(midX - 6f, 700f - dividerH, 12f, dividerH - 20f))")
    sb.appendLine("        }")
    sb.appendLine()
    sb.appendLine("        cups.add(CupData(\"cup_\$i\", cx, cupY, cupRadius, color))")
    sb.appendLine("    }")
    sb.appendLine()
    sb.appendLine("    // Layout templates based on level index and difficulty")
    sb.appendLine("    when (idx % 4) {")
    sb.appendLine("        0 -> { // Standard vertical stack with funnel ramps")
    sb.appendLine("            walls.add(WallSegment(30f, 250f, 100f, 12f)) // Left ramp")
    sb.appendLine("            walls.add(WallSegment(270f, 250f, 100f, 12f)) // Right ramp")
    sb.appendLine("            for (i in 0 until cupCount) {")
    sb.appendLine("                val frac = (i + 0.5f) / cupCount.toFloat()")
    sb.appendLine("                val cx = left + interior * frac")
    sb.appendLine("                val color = (i % 8) + 1")
    sb.appendLine("                balls.add(BallSpawn(\"ball_\$i\", cx, 580f, color, 16f))")
    sb.appendLine("                val pullDx = if (i % 2 == 0) 1f else -1f")
    sb.appendLine("                pins.add(PinData(\"pin_\$i\", cx - 45f, 610f, 90f, 10f, pullDx, 0f))")
    sb.appendLine("                if (hasGrey) {")
    sb.appendLine("                    balls.add(BallSpawn(\"ball_\${i}_g\", cx, 440f, 0, 16f))")
    sb.appendLine("                    pins.add(PinData(\"pin_\${i}_g\", cx - 45f, 480f, 90f, 10f, -pullDx, 0f))")
    sb.appendLine("                }")
    sb.appendLine("            }")
    sb.appendLine("        }")
    sb.appendLine("        1 -> { // Central mixing chamber layout")
    sb.appendLine("            val midX = 200f")
    sb.appendLine("            walls.add(WallSegment(60f, 200f, 120f, 12f))")
    sb.appendLine("            walls.add(WallSegment(220f, 200f, 120f, 12f))")
    sb.appendLine("            pins.add(PinData(\"pin_center_mix\", midX - 60f, 320f, 120f, 12f, 1f, 0f))")
    sb.appendLine("            for (i in 0 until cupCount) {")
    sb.appendLine("                val frac = (i + 0.5f) / cupCount.toFloat()")
    sb.appendLine("                val cx = left + interior * frac")
    sb.appendLine("                val color = (i % 8) + 1")
    sb.appendLine("                balls.add(BallSpawn(\"ball_\$i\", cx, 520f, color, 16f))")
    sb.appendLine("                pins.add(PinData(\"pin_\$i\", cx - 40f, 560f, 80f, 10f, if (i % 2 == 0) -1f else 1f, 0f))")
    sb.appendLine("                if (hasGrey) {")
    sb.appendLine("                    balls.add(BallSpawn(\"ball_\${i}_g\", midX + (i - cupCount / 2f) * 30f, 150f, 0, 16f))")
    sb.appendLine("                }")
    sb.appendLine("            }")
    sb.appendLine("        }")
    sb.appendLine("        2 -> { // Multi-tier staggered pins")
    sb.appendLine("            for (i in 0 until cupCount) {")
    sb.appendLine("                val frac = (i + 0.5f) / cupCount.toFloat()")
    sb.appendLine("                val cx = left + interior * frac")
    sb.appendLine("                val color = (i % 8) + 1")
    sb.appendLine("                balls.add(BallSpawn(\"ball_\$i\", cx, 560f - i * 20f, color, 16f))")
    sb.appendLine("                pins.add(PinData(\"pin_\$i\", cx - 45f, 600f - i * 20f, 90f, 10f, 1f, 0f))")
    sb.appendLine("                if (hasGrey) {")
    sb.appendLine("                    balls.add(BallSpawn(\"ball_\${i}_g\", cx, 360f - i * 20f, 0, 16f))")
    sb.appendLine("                    pins.add(PinData(\"pin_\${i}_g\", cx - 45f, 400f - i * 20f, 90f, 10f, -1f, 0f))")
    sb.appendLine("                }")
    sb.appendLine("            }")
    sb.appendLine("        }")
    sb.appendLine("        else -> { // Cross-chamber funnel layout")
    sb.appendLine("            walls.add(WallSegment(40f, 180f, 140f, 12f))")
    sb.appendLine("            walls.add(WallSegment(220f, 300f, 140f, 12f))")
    sb.appendLine("            for (i in 0 until cupCount) {")
    sb.appendLine("                val frac = (i + 0.5f) / cupCount.toFloat()")
    sb.appendLine("                val cx = left + interior * frac")
    sb.appendLine("                val color = (i % 8) + 1")
    sb.appendLine("                balls.add(BallSpawn(\"ball_\$i\", cx, 540f, color, 16f))")
    sb.appendLine("                pins.add(PinData(\"pin_\$i\", cx - 45f, 580f, 90f, 10f, if (i % 2 == 0) 1f else -1f, 0f))")
    sb.appendLine("                if (hasGrey) {")
    sb.appendLine("                    balls.add(BallSpawn(\"ball_\${i}_g\", cx, 380f, 0, 16f))")
    sb.appendLine("                    pins.add(PinData(\"pin_\${i}_g\", cx - 45f, 420f, 90f, 10f, if (i % 2 == 0) -1f else 1f, 0f))")
    sb.appendLine("                }")
    sb.appendLine("            }")
    sb.appendLine("        }")
    sb.appendLine("    }")
    sb.appendLine()
    sb.appendLine("    return PullPinLevel(id, difficulty, walls, cups, pins, balls)")
    sb.appendLine("}")
    sb.appendLine()
    sb.appendLine("private fun levelsFor(difficulty: String, count: Int): List<PullPinLevel> {")
    sb.appendLine("    return List(count) { idx ->")
    sb.appendLine("        val id = \"pullpin_\${difficulty.lowercase()}_\${(idx + 1).toString().padStart(3, '0')}\"")
    sb.appendLine("        makeLevel(id, difficulty, idx)")
    sb.appendLine("    }")
    sb.appendLine("}")
    sb.appendLine()
    sb.appendLine("object PullPinPregenerated {")
    sb.appendLine("    val ALL_LEVELS: List<PullPinLevel> = buildList {")
    sb.appendLine("        addAll(levelsFor(\"Easy\", 12))")
    sb.appendLine("        addAll(levelsFor(\"Medium\", 12))")
    sb.appendLine("        addAll(levelsFor(\"Hard\", 12))")
    sb.appendLine("        addAll(levelsFor(\"Expert\", 12))")
    sb.appendLine("    }")
    sb.appendLine()
    sb.appendLine("    val PUZZLES_BY_DIFFICULTY: Map<String, List<PullPinLevel>> = ALL_LEVELS.groupBy { it.difficulty }")
    sb.appendLine("}")

    targetFile.parentFile?.mkdirs()
    targetFile.writeText(sb.toString())
    println("Successfully generated Pull Pin layout definitions into ${targetFile.path}")
}

fun main() {
    main(emptyArray())
}
